# Generated by Django 4.2 on 2023-04-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentedImage', models.ImageField(blank=True, null=True, upload_to='images/results/')),
                ('segImg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.imag')),
            ],
            options={
                'db_table': 'segmented_images',
            },
        ),
    ]
