# Generated by Django 4.2 on 2023-04-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_segmentedimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
