# Generated by Django 4.2 on 2023-04-09 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_point_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sugImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/suggestions/"
                    ),
                ),
                (
                    "sugImg_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.imag",
                    ),
                ),
            ],
            options={
                "db_table": "suggested_images",
            },
        ),
    ]
