# Generated by Django 4.2 on 2023-04-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_segmentedimages_segmentedimagemask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentedimages',
            name='segmentedImageMask',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
