# Generated by Django 4.2 on 2023-04-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_segmentedimages_segmentedimagemask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentedimages',
            name='segmentedImageMask',
        ),
    ]
